spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/superstore
    username: root
    password: India@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
        show-sql: true
aws:
  sns:
    topic:
      arn: arn:aws:sns:eu-west-2:850995580792:superstore-notifications